const item = {
    kharazhan: [
        "Royal Cloak of Arathi Kings",
        "Shadow-Cloak of Dalaran",
        "Shadowvine Cloak of Infusion",
        "Gilded Thorium Cloak",
        "Drape of the Dark Reavers",
        "Farstrider Wildercloak",
        "Stainless Cloak of the Pure Hearted",
        "Ruby Drape of the Mysticant",
        "Masquerade Gown",
        "Panzar'Thar Breastplate",
        "Scaled Breastplate of Carnage",
        "Stonebough Jerkin",
        "Chestguard of the Conniver",
        "Robe of the Elder Scribes",
        "Breastplate of the Lightbinder",
        "Earthblood Chestguard",
        "Boots of Foretelling",
        "Edgewalker Longboots",
        "Boots of Valiance",
        "Ruby Slippers",
        "Ironstriders of Urgency",
        "Ferocious Swift-Kickers",
        "Boots of the Incorrupt",
        "Rapscallion Boots",
        "Boots of the Infernal Coven",
        "Boots of Elusion",
        "Spectral Band of Innervation",
        "Garona's Signet Ring",
        "Mender's Heart-Ring",
        "Shermanar Great-Ring",
        "Mithril Band of the Unscarred",
        "Ring of a Thousand Marks",
        "Jade Ring of the Everliving",
        "Gauntlets of Renewed Hope",
        "Gloves of Dexterous Manipulation",
        "Handwraps of Flowing Thought",
        "Gloves of Saintly Blessings",
        "Iron Gauntlets of the Maiden",
        "Gloves of Quickening",
        "Gloves of Centering",
        "Mitts of the Treemender",
        "Grasp of the Dead",
        "Big Bad Wolf's Head",
        "Wicked Witch's Hat",
        "Steelspine Faceguard",
        "Cowl of Defiance",
        "Uni-Mind Headdress",
        "Earthsoul Leggings",
        "Trial-Fire Trousers",
        "Wrynn Dynasty Greaves",
        "Rip-Flayer Leggings",
        "Skulker's Greaves",
        "Pantaloons of Repentance",
        "Shard of the Virtuous",
        "Big Bad Wolf's Paw",
        "Fool's Bane",
        "The Decapitator",
        "Nathrezim Mindblade",
        "Light's Justice",
        "Worgen Claw Necklace",
        "Barbed Choker of Discipline",
        "Brooch of Unquenchable Fury",
        "Emberspur Talisman",
        "Saberclaw Talisman",
        "Shining Chain of the Afterworld",
        "Adornment of Stolen Souls",
        "Ritssyn's Lost Pendant",
        "Signet of Unshakable Faith",
        "Talisman of Nightbane",
        "Aran's Soothing Sapphire",
        "Jewel of Infinite Possibilities",
        "Emerald Ripper",
        "Spiteblade",
        "Malchazeen",
        "Steelhawk Crossbow",
        "Wolfslayer Sniper Rifle",
        "Tirisfal Wand of Ascendancy",
        "Sunfury Bow of the Phoenix",
        "Totem of Healing Rains",
        "Idol of the Avian Heart",
        "Libram of Souls Redeemed",
        "Shield of Impenetrable Darkness",
        "Dragonheart Flameshield",
        "Beastmaw Pauldrons",
        "Pauldrons of the Solace-Giver",
        "Dragon-Quake Shoulderguards",
        "Forest Wind Shoulderpads",
        "Pauldrons of the Justice-Seeker",
        "Mantle of the Mind Flayer",
        "Mantle of Abrahmis",
        "Xavian Stiletto",
        "Gloves of the Fallen HeroHunter, Mage, Warlock",
        "Gloves of the Fallen ChampionPaladin, Rogue, Shaman",
        "Gloves of the Fallen DefenderDruid, Priest, Warrior",
        "Helm of the Fallen HeroHunter, Mage, Warlock",
        "Helm of the Fallen ChampionPaladin, Rogue, Shaman",
        "Helm of the Fallen DefenderDruid, Priest, Warrior",
        "Moroes' Lucky Pocket Watch",
        "Ribbon of Sacrifice",
        "Pendant of the Violet Eye",
        "The Lightning Capacitor",
        "Legacy",
        "Nightstaff of the Everliving",
        "Staff of Infinite Mysteries",
        "Terestian's Stranglestaff",
        "Gorehowl",
        "Nethershard Girdle",
        "Crimson Girdle of the Indomitable",
        "Belt of Gale Force",
        "Cincture of Will",
        "Malefic Girdle",
        "Cord of Nature's Sustenance",
        "Girdle of the Prowler",
        "Girdle of Truth",
        "Bracers of the White Stag",
        "Stalker's War Bands",
        "Harbinger Bands",
        "Vambraces of Courage",
        "Whirlwind Bracers",
        "Bands of Indwelling",
        "Bracers of Justice",
        "Bracers of Maliciousness",
        "Bands of Nefarious Deeds",
        "Ravager's Cuffs",
        "Ravager's Wrist-Wraps",
        "Ravager's Bands",
        "Ravager's Bracers"
    ],
    gruul: [
        "Brute Cloak of the Ogre-Magi",
        "Windshear Boots",
        "Gantlets of Martial Perfection",
        "Gantlets of the Dragonslayer",
        "Malefic Mask of the Shadows",
        "Collar of Cho'gall",
        "Maulgar's Warhelm",
        "Cowl of Nature's Breath",
        "Bloodmaw Magus-Blade",
        "Teeth of Gruul",
        "Aldori Legacy Defender",
        "Shuriken of Negation",
        "Dragonspine Trophy",
        "Eye of Gruul",
        "Hammer of the Naaru",
        "Axe of the Gronn Lords",
        "Gronn-Stitched Girdle",
        "Belt of Divine Inspiration",
        "Bladespire Warbands"
    ],
    magtheridon: [
        "Cloak of the Pit Stalker",
        "Soul-Eater's Handwraps",
        "Liar's Tongue Gloves",
        "Thundering Greathelm",
        "Aegis of the Vindicator",
        "Karaborian Talisman",
        "Eredar Wand of Obliteration",
        "Eye of Magtheridon",
        "Crystalheart Pulse-staff",
        "Glaive of the Pit",
        "Girdle of the Endless Pit",
        "Terror Pit Gridle"
    ]
}